config/routes.rb
Rails.application.routes.draw do
  resources :people
  resources :phone_numbers

  root 'people#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessor :title
  has_many :phone_numbers

  validates :name, presence: true
  validates :title, presence: true

  def to_s
    name
  end
end

app/models/phone_number.rb
class PhoneNumber < ActiveRecord::Base
  belongs_to :person

  validates :name, presence: true
  validates :number, presence: true

  validates :start_year, numericality: {allow_nil: true}
  validates :end_year, numericality: {greater_than_or_equal_to: :start_year, allow_nil: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  def index
    @people = Person.all
  end

  # GET /people/1
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to @person, notice: 'Person was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /people/1
  def update
    if @person.update(person_params)
      redirect_to @person, notice: 'Person was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /people/1
  def destroy
    @person.destroy
    redirect_to people_url, notice: 'Person was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def person_params
      params.require(:person).permit(:name, :title)
    end
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  before_action :set_phone_number, only: [:show, :edit, :update, :destroy]

  # GET /phone_numbers
  # GET /phone_numbers.json
  def index
    @phone_numbers = PhoneNumber.all
  end

  # GET /phone_numbers/1
  # GET /phone_numbers/1.json
  def show
  end

  # GET /phone_numbers/new
  def new
    @phone_number = PhoneNumber.new
  end

  # GET /phone_numbers/1/edit
  def edit
  end

  # POST /phone_numbers
  # POST /phone_numbers.json
  def create
    @phone_number = PhoneNumber.new(phone_number_params)

    respond_to do |format|
      if @phone_number.save
        format.html { redirect_to @phone_number, notice: 'Phone number was successfully created.' }
        format.json { render :show, status: :created, location: @phone_number }
      else
        format.html { render :new }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_numbers/1
  # PATCH/PUT /phone_numbers/1.json
  def update
    respond_to do |format|
      if @phone_number.update(phone_number_params)
        format.html { redirect_to @phone_number, notice: 'Phone number was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone_number }
      else
        format.html { render :edit }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_numbers/1
  # DELETE /phone_numbers/1.json
  def destroy
    @phone_number.destroy
    respond_to do |format|
      format.html { redirect_to phone_numbers_url, notice: 'Phone number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_phone_number
    @phone_number = PhoneNumber.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def phone_number_params
    params.require(:phone_number).permit(:name, :country_code, :number, :person_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Phone Numbers:</strong>
  <ul>
    <% @person.phone_numbers.each do |phone_number| %>
      <li>
        <%= phone_number.name %>: <%= phone_number.number %>
        <%= link_to "Edit", edit_phone_number_path(phone_number) %>
      </li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/phone_numbers/_form.html.erb
<%= form_for(@phone_number) do |f| %>
  <% if @phone_number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phone_number.errors.count, "error") %> prohibited this phone_number from being saved:</h2>

      <ul>
      <% @phone_number.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :person_id %><br>
    <%= f.collection_select :person_id, Person.all, :id, :name, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country_code %><br>
    <%= f.number_field :country_code %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phone_numbers/edit.html.erb
<h1>Editing phone_number</h1>

<%= render 'form' %>

<%= link_to 'Show', @phone_number %> |
<%= link_to 'Back', phone_numbers_path %>

app/views/phone_numbers/index.html.erb
<h1>Listing phone_numbers</h1>

<table>
  <thead>
    <tr>
      <th>Person</th>
      <th>Name</th>
      <th>Country code</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phone_numbers.each do |phone_number| %>
      <tr>
        <td>
          <% if phone_number.person %>
            <%= link_to phone_number.person, phone_number.person %>
          <% end %>
        </td>
        <td><%= phone_number.name %></td>
        <td><%= phone_number.country_code %></td>
        <td><%= phone_number.number %></td>
        <td><%= link_to 'Show', phone_number %></td>
        <td><%= link_to 'Edit', edit_phone_number_path(phone_number) %></td>
        <td><%= link_to 'Destroy', phone_number, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phone number', new_phone_number_path %>

app/views/phone_numbers/new.html.erb
<h1>New phone_number</h1>

<%= render 'form' %>

<%= link_to 'Back', phone_numbers_path %>

app/views/phone_numbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Person ID:</strong>
  <%= @phone_number.person_id %>
</p>

<% if @phone_number.person %>
  <p>
    <strong>Person:</strong>
    <%= link_to @phone_number.person, @phone_number.person %>
  </p>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @phone_number.name %>
</p>

<p>
  <strong>Country code:</strong>
  <%= @phone_number.country_code %>
</p>

<p>
  <strong>Number:</strong>
  <%= @phone_number.number %>
</p>

<%= link_to 'Edit', edit_phone_number_path(@phone_number) %> |
<%= link_to 'Back', phone_numbers_path %>